name: Keep Grafana Instance Active
on:
  schedule:
    - cron: '0 0/6 * * *'

jobs:
  keep-grafana-instance-active:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Send log to Grafana Cloud
        run: |
          curl --fail-with-body -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.TEST_GRAFANA_CLOUD_STACK_LOGS_USER_ID }}:${{ secrets.TEST_GRAFANA_CLOUD_TOKEN }}" -d '{"streams": [{"stream": {"Language": "Curl", "source": "GitHub Actions"},"values": [["'"$(($(date +%s)*1000000000))"'", "Keeping this Grafana instance alive!"]]}]}' https://logs-prod-006.grafana.net/loki/api/v1/push

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}