name: Keep Grafana Instance Active
on:
  schedule:
    - cron: '0 0/3 * * *'

jobs:
  keep-grafana-instance-active:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get home dashboard
        run: |
          curl --fail-with-body -X GET -H "Authorization: Bearer ${{ secrets.TEST_GRAFANA_INSTANCE_API_TOKEN }}" https://${{ secrets.TEST_GRAFANA_CLOUD_STACK_SLUG }}.grafana.net/api/dashboards/home

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}