name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables from .env
        uses: xom9ikk/dotenv@v2.2.0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v{{ env.GORELEASER_VERSION }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}